/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as CardapioSlugRouteImport } from './routes/cardapio.$slug'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel/index'
import { Route as AuthenticatedPainelPedidosRouteImport } from './routes/_authenticated/painel/pedidos'
import { Route as AuthenticatedPainelMesasRouteImport } from './routes/_authenticated/painel/mesas'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel/configuracoes'
import { Route as AuthenticatedPainelCardapioRouteImport } from './routes/_authenticated/painel/cardapio'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioSlugRoute = CardapioSlugRouteImport.update({
  id: '/cardapio/$slug',
  path: '/cardapio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPedidosRoute =
  AuthenticatedPainelPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelMesasRoute =
  AuthenticatedPainelMesasRouteImport.update({
    id: '/mesas',
    path: '/mesas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCardapioRoute =
  AuthenticatedPainelCardapioRouteImport.update({
    id: '/cardapio',
    path: '/cardapio',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/painel/cardapio': typeof AuthenticatedPainelCardapioRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/mesas': typeof AuthenticatedPainelMesasRoute
  '/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/painel/cardapio': typeof AuthenticatedPainelCardapioRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/mesas': typeof AuthenticatedPainelMesasRoute
  '/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/cardapio/$slug': typeof CardapioSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/_authenticated/painel/cardapio': typeof AuthenticatedPainelCardapioRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/mesas': typeof AuthenticatedPainelMesasRoute
  '/_authenticated/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/cardapio/$slug'
    | '/pedido/$id'
    | '/painel/cardapio'
    | '/painel/configuracoes'
    | '/painel/mesas'
    | '/painel/pedidos'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/cardapio/$slug'
    | '/pedido/$id'
    | '/painel/cardapio'
    | '/painel/configuracoes'
    | '/painel/mesas'
    | '/painel/pedidos'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/painel'
    | '/cardapio/$slug'
    | '/pedido/$id'
    | '/_authenticated/painel/cardapio'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/mesas'
    | '/_authenticated/painel/pedidos'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  CardapioSlugRoute: typeof CardapioSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio/$slug': {
      id: '/cardapio/$slug'
      path: '/cardapio/$slug'
      fullPath: '/cardapio/$slug'
      preLoaderRoute: typeof CardapioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pedidos': {
      id: '/_authenticated/painel/pedidos'
      path: '/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof AuthenticatedPainelPedidosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/mesas': {
      id: '/_authenticated/painel/mesas'
      path: '/mesas'
      fullPath: '/painel/mesas'
      preLoaderRoute: typeof AuthenticatedPainelMesasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/cardapio': {
      id: '/_authenticated/painel/cardapio'
      path: '/cardapio'
      fullPath: '/painel/cardapio'
      preLoaderRoute: typeof AuthenticatedPainelCardapioRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelCardapioRoute: typeof AuthenticatedPainelCardapioRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelMesasRoute: typeof AuthenticatedPainelMesasRoute
  AuthenticatedPainelPedidosRoute: typeof AuthenticatedPainelPedidosRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelCardapioRoute: AuthenticatedPainelCardapioRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelMesasRoute: AuthenticatedPainelMesasRoute,
  AuthenticatedPainelPedidosRoute: AuthenticatedPainelPedidosRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  CardapioSlugRoute: CardapioSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
